basket/urls.py
from django.urls import path
from .views import view_basket, add_to_basket, amend_basket, delete_from_basket


app_name = 'basket'
urlpatterns = [
    path('', view_basket, name='view_basket'),
    path('add/<id>/', add_to_basket, name='add_to_basket'),
    path('amend/<id>/', amend_basket, name='amend_basket'),
    path('delete/<id>/', delete_from_basket, name='delete_from_basket'),
]

checkout/urls.py
from django.urls import path
from checkout.views import checkout, checkout_success, checkout_history, order_detail, bespoke
from .webhooks import webhook

app_name = 'checkout'
urlpatterns = [
    path('', checkout, name='checkout'),
    path('success/<order_number>/', checkout_success, name='checkout_success'),
    path('checkout_history/', checkout_history, name='checkout_history'),
    path('order_detail/<order_number>', order_detail, name='order_detail'),
    path('bespoke/<order_number>/<id>/', bespoke, name='bespoke'),
    path('wh/', webhook, name='webhook'),
]

home/urls.py
from django.urls import path
from profiles.views import testimonial

app_name = 'home'
urlpatterns = [
    path('testimonial/', testimonial, name='testimonial'),
]

products/urls.py
from django.urls import path
from products.views import view_products, view_products_by_type, view_product, review_product


app_name = 'products'
urlpatterns = [
    path('', view_products, name='view_products'),
    path('products_by_type/<product_type>/', view_products_by_type,
         name='view_products_by_type'),
    path('view-product/<id>/', view_product, name='view_product'),
    path('review-product/<id>/', review_product, name='review_product'),
]

profiles/urls.py
from django.urls import path
from .views import my_profile, my_details

app_name = 'profiles'
urlpatterns = [
    path('', my_profile, name='my_profile'),
    path('my_details/', my_details, name='my_details')
]

tartanthom/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls', namespace=None)),
    path('about/', include('about.urls', namespace=None)),
    path('contact/', include('contact.urls', namespace=None)),
    path('products/', include('products.urls', namespace=None)),
    path('basket/', include('basket.urls', namespace=None)),
    path('checkout/', include('checkout.urls', namespace=None)),
    path('profiles/', include('profiles.urls', namespace=None)),
    path('home/', include('home.urls', namespace=None)),
    path('', index, name='index'),
]

checkout/models.py
import uuid
from django.db.models import Sum
from django.db import models
from products.models import Products
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.conf import settings
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

# Create your models here.


class Order(models.Model):
    order_user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, default='')
    order_number = models.CharField(max_length=32)
    fullname = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=20)
    date = models.DateTimeField(auto_now_add=True)
    address_line1 = models.CharField(max_length=50)
    address_line2 = models.CharField(max_length=50)
    town_city = models.CharField(max_length=30)
    postcode = models.CharField(max_length=10)
    country = CountryField(blank_label='Country', max_length=30)
    order_total = models.DecimalField(default=0, decimal_places=2, max_digits=6)
    delivery_total = models.DecimalField(default=0, decimal_places=2, max_digits=6)
    grand_total = models.DecimalField(default=0, decimal_places=2, max_digits=6)
    is_complete = models.BooleanField(default=False)

    def create_order_number(self):
        """
        Generates unique order number for order
        """
        return uuid.uuid4().hex.upper()

    def save(self, *args, **kwargs):
        """
        Overrides save method on order model for order number where
        it does not already exist
        """
        if not self.order_number:
            self.order_number = self.create_order_number()
        super().save(*args, **kwargs)

    def update_total(self):
        """
        Update order total, delivery and grand total as line items
        are added, updated or deleted
        """
        self.order_total = self.lineitems.aggregate(
            Sum('item_total'))['item_total__sum'] or 0
        if self.order_total < settings.MIN_DELIVERY_THRESHOLD:
            self.delivery_total = settings.MIN_DELIVERY_CHARGE
        else:
            self.delivery_total = settings.UPPER_DELIVERY_CHARGE
        self.grand_total = float(self.order_total) + float(self.delivery_total)
        self.save()

    def __str__(self):
        return self.fullname


class OrderItem(models.Model):
    order = models.ForeignKey(Order, null=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(Products, null=False, on_delete=models.CASCADE)
    quantity = models.IntegerField(blank=False)
    item_total = models.DecimalField(max_digits=8, decimal_places=2, null=False,blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Calculate total of order item depending on whether the
        item is on sale or full price
        """
        if not self.product.sale_price:
            self.item_total = self.product.price * self.quantity
        else:
            self.item_total = self.product.sale_price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return self.product.name


class Bespoke(models.Model):
    class Meta:

        verbose_name_plural = 'Bespoke'

    bespoke_order = models.ForeignKey(Order, null=False, on_delete=models.CASCADE)
    bespoke_product = models.ForeignKey(Products, null=False, on_delete=models.CASCADE)
    person_name1 = models.CharField(max_length=50, blank=True, null=True)
    person_name2 = models.CharField(max_length=50, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    place_of_birth = models.CharField(max_length=50, blank=True, null=True)
    birth_weight_lb = models.IntegerField(blank=True, null=True)
    birth_weight_oz = models.IntegerField(blank=True, null=True)
    wedding_date = models.DateField(blank=True, null=True)
    address_line1 = models.CharField(max_length=50, blank=True, null=True)
    is_complete = models.BooleanField(blank=True, default=False)


# Signals

@receiver(post_save, sender=OrderItem)
def update_on_save(sender, instance, created, **kwargs):
    """
    Signal listens for change on OrderItem and updates order
    totals where items in an order are created or updated
    """
    instance.order.update_total()


@receiver(post_delete, sender=OrderItem)
def update_on_delete(sender, instance, **kwargs):
    """
    Signal listens for change on OrderItem and updates order
    totals where items in an order are deleted
    """
    instance.order.update_total()

checkout/forms.py
from django import forms
from checkout.models import Order
from .models import Bespoke


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('fullname', 'phone_number', 'address_line1',
                  'address_line2', 'town_city', 'postcode', 'country')


class BespokeForm(forms.ModelForm):

    wedding_date = forms.DateField(widget=forms.SelectDateWidget(
        years=range(1900, 2040)), required=False)
    date_of_birth = forms.DateField(widget=forms.SelectDateWidget(
        years=range(1900, 2040)), required=False)

    class Meta:
        model = Bespoke

        fields = ('person_name1', 'person_name2', 'date_of_birth',
                  'place_of_birth', 'birth_weight_lb', 'birth_weight_oz',
                  'address_line1')

        labels = {
            'person_name1': 'Name',
            'person_name2': 'Name of Person 2',
            'date_of_birth': 'Date of Birth',
            'place_of_birth': 'Place of Birth',
            'birth_weight_lb': 'Birth Weight (lb)',
            'birth_weight_oz': 'Birth Weight (oz)',
            'wedding_date': 'Date of wedding',
            'address_line1': 'Address'
        }

        help_texts = {
            'birth_weight_lb': 'Enter birth weight pounds',
            'birth_weight_oz': 'Enter birth weight ounces',
            'address_line1': 'Enter house no and street name',
        }

checkout/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.conf import settings
from checkout.forms import OrderForm, BespokeForm
from .models import Order, OrderItem
from products.models import Products
from basket.contexts import basket_contents
from django.contrib import messages
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
import stripe
import os

# Create your views here.


@login_required
def checkout(request):
    """
    Creates order from basket items, takes payment through Stripe and
    emails user receipt
    """
    stripe_public_key = settings.STRIPE_PUBLIC_KEY
    stripe_secret_key = settings.STRIPE_SECRET_KEY
    if request.method == 'POST':
        basket = request.session.get('basket', {})
        form_data = {
            'fullname': request.POST['fullname'],
            'phone_number': request.POST['phone_number'],
            'address_line1': request.POST['address_line1'],
            'address_line2': request.POST['address_line2'],
            'town_city': request.POST['town_city'],
            'postcode': request.POST['postcode'],
            'country': request.POST['country'],
        }
        order_form = OrderForm(form_data)

        if order_form.is_valid():
            order = order_form.save(commit=False)
            order.order_user = request.user
            order.save()
            for id, quantity in basket.items():
                try:
                    product = Products.objects.get(pk=id)
                    order_item = OrderItem(
                        order=order,
                        product=product,
                        quantity=quantity
                    )
                    order_item.save()
                    del request.session['basket']
                    del request.session['product_count']
                    request.session.modified = True

                    context = {
                        'order': order,
                    }
                    from_email = os.environ.get('EMAIL_USER')
                    user = request.user
                    header = "Tartan Thom Receipt"
                    html_message = render_to_string('checkout/receipt.html', context)
                    plain_message = strip_tags(html_message)
                    send_mail(header, plain_message, from_email, [user.email], html_message=html_message, fail_silently=False)

                except Products.DoesNotExist:
                    order.delete()
            return redirect(reverse('checkout:checkout_success', args=[order.order_number]))
        else:
            messages.error(request, "Please review the details in the order form")
    else:
        basket = request.session.get('basket', {})
        current_contents = basket_contents(request)
        grand_total = current_contents['grand_total']
        stripe_total = round(grand_total * 100)
        stripe.api_key = stripe_secret_key
        intent = stripe.PaymentIntent.create(
            amount=stripe_total,
            currency=settings.STRIPE_CURRENCY
        )
        order_form = OrderForm()
        context = {
            'order_form': order_form,
            'stripe_public_key': stripe_public_key,
            'client_secret': intent.client_secret,
        }

    return render(request, 'checkout/checkout.html', context)


@login_required
def checkout_success(request, order_number):
    """
    Return success page on successful checkout showing order detail
    """
    order = get_object_or_404(Order, order_number=order_number)

    return render(request, 'checkout/success.html', {'order': order})


@login_required
def checkout_history(request):
    """
    Returns a list of previous orders for the logged in user
    """
    user = request.user
    user_orders = Order.objects.filter(order_user=user).order_by('-date')
    if user_orders:
        context = {
            'user_orders': user_orders,
        }
    else:
        messages.error(request, "Sorry, you don't currently have any orders")
        return redirect(reverse('profiles:my_profile'))

    return render(request, 'checkout/checkout_history.html', context)


@login_required
def order_detail(request, order_number):
    """
    Return details of an individual order and the items within the order
    """
    order = get_object_or_404(Order, order_number=order_number)
    context = {
        'order': order,
    }
    return render(request, 'checkout/order_detail.html', context)


@login_required
def bespoke(request, order_number, id):
    """
    Returns a bespoke form for users to complete further information for
    order items
    """
    form = BespokeForm()
    product = get_object_or_404(Products, pk=id)
    order = get_object_or_404(Order, order_number=order_number)
    context = {
        'form': form,
        'order': order,
        'product': product,
    }
    if request.method == 'POST':
        form = BespokeForm(request.POST)
        if form.is_valid():
            bespoke = form.save(commit=False)
            bespoke.bespoke_order = order
            bespoke.bespoke_product = product
            bespoke.save()
            messages.success(request, 'Thanks for submitting your bespoke details!')
            return redirect(reverse('checkout:order_detail', args=(order_number, )))
        else:
            messages.error(request, 'Please check the information in the form')

    return render(request, 'checkout/bespoke.html', context)

checkout/templates/checkout/bespoke.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap_tags %}
{% load crispy_forms_tags %}
{% block title %}Tartan Thom - Bespoke{% endblock %}

{% block content %}

<div class="container tartan-thom-container p-3 my-5">
    <div class="row justify-content-center m-2 p-3">
        <div class="col-md-12">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <h1>Bespoke Item Form</h1>
                </div>
            </div>

            <div class="row justify-content-center">
                <div class="col-md-8 px-3 mx-auto">

                <form action="{% url 'checkout:bespoke' order.order_number product.id %}" method="POST">
                {% csrf_token %}
                    <!-------------Customer Details----------->
                    <fieldset class="mb-5">
                    <!---------------------Birthday----------------->
                    {% if product.category == 'Birthday' %}
                        {{ form.person_name1|as_crispy_field }}
                        {{ form.date_of_birth|as_crispy_field }}
                    <!----------------------Baby-------------------->
                    {% elif product.category == 'Baby' %}
                        {{ form.person_name1|as_crispy_field }}
                        {{ form.date_of_birth|as_crispy_field }}
                        {{ form.place_of_birth|as_crispy_field }}
                        {{ form.birth_weight_lb|as_crispy_field }}
                        {{ form.birth_weight_oz|as_crispy_field }}
                    <!---------------------New Home----------------->
                    {% elif product.category == 'New Home' %}
                        {{ form.person_name1|as_crispy_field }}
                        {{ form.address_line1|as_crispy_field }}
                    <!------------Anniversary/Wedding--------------->
                    {% elif product.category == 'Anniversary' or 'Wedding' %}
                        {{ form.person_name1|as_crispy_field }}
                        {{ form.person_name2|as_crispy_field }}
                        {{ form.wedding_date|as_crispy_field }}
                    {% else %}
                        <p>Sorry, this doesn't appear to be a bespoke product</p>
                    {% endif %}
                    </fieldset>
                    <fieldset class="mb-5">
                        <button type="submit" class="btn tartan-thom-btn">Submit</button>
                    </fieldset>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>    

{% endblock %}

checkout/templates/checkout/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap_tags %}
{% load crispy_forms_tags %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}
{% block title %}Tartan Thom - Checkout{% endblock %}

{% block content %}


<div class="container tartan-thom-container p-3 my-5">
    <div class="row justify-content-center m-2 p-3">
        <div class="col-md-12">
            <div class="row justify-content-center">
                <div class="col-md-12 col-lg-8 px-3 mx-auto my-2">
                    <h1>Checkout</h1>
                </div>
            </div>

            <div class="row justify-content-center">
                <div class="col-md-12 col-lg-8 px-3 mx-auto my-2">
                    <h2>Checkout Items</h2>
                </div>
            </div>

            {% for item in basket_items %}
            <div class="row justify-content-center m-2">
                <div class="col-md-12 col-lg-8">
                    <div class="row">
                        <div class="col-xs-12 col-md-6 p-1 my-1">
                            <img src="{{ item.product.image.url }}" alt="product-image" class="products-image"/>
                            {% if item.product.label %}
                            <div class="product-label-left py-auto">
                                <span class="label">{{ item.product.label }}</span>
                            </div>
                            {% endif %}
                        </div>

                        <div class="col-xs-12 col-md-6 px-3 my-1 basket-detail">
                            <h2 class="py-3">{{ item.product.name }}</h2>
                            {% if item.product.sale_price %}
                            <p>
                                <span>{{ item.quantity }}</span> x <span>£{{ item.product.sale_price}}</span>
                            </p>
                            {% else %}
                            <p>
                                <span>{{ item.quantity }}</span> x <span>£{{ item.product.price}}</span>
                            </p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            {% endfor %}
            <div class="row justify-content-center my-3">
                <div class="col-md-12 col-lg-8">
                    {% if product_count == 1%}
                        <h3>You are checking out {{ product_count }} item from Tartan Thom</h3>
                    {% else %}
                        <h3>You are checking out {{ product_count }} items from Tartan Thom</h3>
                    {% endif %}
                    <p>Total cost: £{{ grand_total }}</p>
                </div>
                <div class="col-md-12 col-lg-8 my-3">
                    <a href="{% url 'basket:view_basket' %}" class="btn checkout-btn btn-md m-1">Back to bag</a>
                    <a href="{% url 'products:view_products' %}" class="btn checkout-btn btn-md m-1">Continue Shopping</a>

                </div>
            </div>

            <div class="row justify-content-center">
                <div class="col-md-12 col-lg-8">

                    <form action="{% url 'checkout:checkout' %}" method="POST" id="payment-form">
                    {% csrf_token %}
                        <!-------------Customer Details----------->
                        <div class="row">
                            <div class="col px-3">
                                <fieldset class="mb-5">
                                <h2>Customer Details</h2>
                                    <div>
                                        {{ order_form.fullname | as_crispy_field }}
                                        {{ order_form.phone_number | as_crispy_field }}
                                    </div>
                                </fieldset>
                            </div>
                        </div>

                        <!-------------Delivery Address----------->
                        <div class="row">
                            <div class="col px-3">
                                <fieldset class="mb-5">
                                <h2>Delivery Address</h2>
                                    <div>
                                        {{ order_form.address_line1 | as_crispy_field }}
                                        {{ order_form.address_line2 | as_crispy_field }}
                                        {{ order_form.town_city | as_crispy_field }}
                                        {{ order_form.postcode | as_crispy_field }}
                                        {{ order_form.country | as_crispy_field }}
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                        <!-------------Payment Details------------>
                        <div class="row">
                            <div class="col px-3">
                                <fieldset class="mb-5">
                                <h2>Payment</h2>
                                        <div id="card-element">
                                        <!-- Stripe will create input elements here -->
                                        </div>
                                        <!-- Stripe will put the error messages in this element -->
                                        <div id="card-errors" role="alert"></div>
                                </fieldset>
                                <div class="submit-button">
                                    <button id="submit-button" class="btn checkout-btn">Pay</button>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    {{ stripe_public_key|json_script:"id_stripe_public_key" }}
    {{ client_secret|json_script:"id_client_secret" }}
    <script src="{% static 'checkout/js/stripe_elements.js' %}"></script>
{% endblock %}

checkout/templates/checkout/checkout_history.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}Tartan Thom - Order History{% endblock %} 

{% block content %}

<div class="container tartan-thom-container p-3 my-5">
    <div class="row justify-content-center m-2 p-3">
        <div class="col-md-12">
            <div class="row justify-content-center">
                <div class="col-md-8 my-3">
                    <h1>Order History</h1>
                </div>
            </div>
        {% if user_orders %}
            {% for order in user_orders.all %}
            <div class="row justify-content-center">
                <div class="col-md-2">
                    <i class="fas fa-archive fa-3x float-right"></i>
                </div>
                <div class="col-md-8 px-3 mx-auto">
                    <a href="{% url 'checkout:order_detail' order.order_number%}" class="link"><p>Order Number: {{ order.order_number }}</p></a>
                    <p>Order Date: {{ order.date.date }}</p>
                    <p>Total: £{{ order.grand_total }}</p>
                    <p>Ordered By: {{ order.fullname }}</p>
                </div>
            </div>
            <hr>
            {% endfor %}
        {% endif %}

        </div>
    </div>
</div>

{% endblock %}

checkout/templates/checkout/order_detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block title%}Tartan Thom - Order Detail{% endblock %} 

{% block content %}

<div class="container tartan-thom-container p-3 my-5">
    <div class="row justify-content-center m-2 p-3">
        <div class="col-md-12 col-lg-8">
            <div class="row justify-content-center">
                <div class="col-md-12 px-3 mx-auto my-2">
                    <h1>Order Detail</h1>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h3>Order Summary:</h3>
                    <p class="text-break">Order Number: {{ order.order_number }}</p>
                    <p>Date: {{ order.date }}</p>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-6 py-2">
                    <h3>Delivery Details:</h3>
                    <p>{{ order.fullname }}</p>
                    <p>{{ order.address_line1 }}</p>
                    <p>{{ order.address_line2 }}</p>
                    <p>{{ order.town_city }}</p>
                    <p>{{ order.postcode }}</p>
                    <p>{{ order.country }}</p>
                </div>
                <div class="col-md-6 py-2">
                    <h3>Payment Details:</h3>
                    <p>Total Items: £{{ order.order_total }}</p>
                    <p>Delivery charge: £{{ order.delivery_total }}</p>
                    <p>Grand Total: £{{ order.grand_total }}</p>
                </div>
            </div>
            <hr>

        {% if order %}
            {% for item in order.lineitems.all %}
            <div class="row">
                <div class="col-xs-12 col-sm-6 p-2">
                    <a href="{% url 'products:view_product' item.product.id %}"><img src="{{ item.product.image.url }}" alt="product-image" height="200" width="200"></a>
                </div>
                <div class="col-xs-12 col-sm-6 p-2">
                    <h3>{{ item.product.name }}</h3>
                    <p>Quantity: {{ item.quantity }}</p>
                    <p>Product total : £{{ item.item_total }}</p>
                    <a href="{% url 'products:review_product' item.product.id %}" class="btn tartan-thom-btn my-2">Leave a review</a>
                    {% if item.product.is_bespoke %}
                        <a href="{% url 'checkout:bespoke' order.order_number item.product.id %}" class="btn tartan-thom-btn my-2">Bespoke form</a>
                    {% endif %}

                </div>
            </div>
            <hr>
            {% endfor %}
        {% endif %}
        <div>
            <div class="col-md-12 col-lg-8 my-3">
                <a href="{% url 'checkout:checkout_history' %}" class="btn checkout-btn btn-md">Back to Order History</a>
            </div>
        </div>

        </div>
    </div>
</div>

{% endblock %}

checkout/templates/checkout/receipt.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Open+Sans&family=Parisienne&display=swap" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/all.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

<div class="container tartan-thom-container p-3 my-5">
    <div class="row justify-content-center m-2 p-3">
        <div class="col-md-12 col-lg-8">
            <div class="row justify-content-center">
                <div class="col-md-12 px-3 mx-auto my-2">
                    <h1>Tartan Thom Receipt</h1>
                    <h3>Please retain this receipt as proof of purchase</h3>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h3>Order Summary:</h3>
                    <p class="text-break">Order Number: {{ order.order_number }}</p>
                    <p>Date: {{ order.date }}</p>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-6 py-2">
                    <h3>Delivery Details:</h3>
                    <p>{{ order.fullname }}</p>
                    <p>{{ order.address_line1 }}</p>
                    <p>{{ order.address_line2 }}</p>
                    <p>{{ order.town_city }}</p>
                    <p>{{ order.postcode }}</p>
                    <p>{{ order.country }}</p>
                </div>
                <div class="col-md-6 py-2">
                    <h3>Payment Details:</h3>
                    <p>Total Items: £{{ order.order_total }}</p>
                    <p>Delivery charge: £{{ order.delivery_total }}</p>
                    <p>Grand Total: £{{ order.grand_total }}</p>
                </div>
            </div>
            <hr>

        {% if order %}
            {% for item in order.lineitems.all %}
            <div class="row">
                <div class="col-xs-12 col-sm-6 p-2">
                    <a href="{% url 'products:view_product' item.product.id %}"><img src="{{ item.product.image.url }}" alt="product-image" height="200" width="200"></a>
                </div>
                <div class="col-xs-12 col-sm-6 p-2">
                    <h3>{{ item.product.name }}</h3>
                    <p>Quantity: {{ item.quantity }}</p>
                    <p>Product total : £{{ item.item_total }}</p>
                    {% if item.product.is_bespoke %}
                        <p>Please login to Tartan Thom to complete our bespoke order form</p>
                    {% endif %}
                </div>
            </div>
            <hr>
            {% endfor %}
        {% endif %}
        </div>
    </div>
</div>