basket/urls.py
from django.urls import path
from .views import view_basket, add_to_basket, amend_basket, delete_from_basket


app_name = 'basket'
urlpatterns = [
    path('', view_basket, name='view_basket'),
    path('add/<id>/', add_to_basket, name='add_to_basket'),
    path('amend/<id>/', amend_basket, name='amend_basket'),
    path('delete/<id>/', delete_from_basket, name='delete_from_basket'),
]

checkout/urls.py
from django.urls import path
from checkout.views import checkout, checkout_success, checkout_history, order_detail, bespoke
from .webhooks import webhook

app_name = 'checkout'
urlpatterns = [
    path('', checkout, name='checkout'),
    path('success/<order_number>/', checkout_success, name='checkout_success'),
    path('checkout_history/', checkout_history, name='checkout_history'),
    path('order_detail/<order_number>', order_detail, name='order_detail'),
    path('bespoke/<order_number>/<id>/', bespoke, name='bespoke'),
    path('wh/', webhook, name='webhook'),
]

home/urls.py
from django.urls import path
from profiles.views import testimonial

app_name = 'home'
urlpatterns = [
    path('testimonial/', testimonial, name='testimonial'),
]

products/urls.py
from django.urls import path
from products.views import view_products, view_products_by_type, view_product, review_product


app_name = 'products'
urlpatterns = [
    path('', view_products, name='view_products'),
    path('products_by_type/<product_type>/', view_products_by_type,
         name='view_products_by_type'),
    path('view-product/<id>/', view_product, name='view_product'),
    path('review-product/<id>/', review_product, name='review_product'),
]

tartanthom/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls', namespace=None)),
    path('about/', include('about.urls', namespace=None)),
    path('contact/', include('contact.urls', namespace=None)),
    path('products/', include('products.urls', namespace=None)),
    path('basket/', include('basket.urls', namespace=None)),
    path('checkout/', include('checkout.urls', namespace=None)),
    path('profiles/', include('profiles.urls', namespace=None)),
    path('home/', include('home.urls', namespace=None)),
    path('', index, name='index'),
]

basket/views.py
from django.shortcuts import render

# Create your views here.


def view_basket(request):
    """
    A view that renders the contents of the basket
    """
    return render(request, 'basket/basket.html')


def add_to_basket(request, id):
    """
    A view that adds the quantity of a product to the basket
    """
    quantity = int(request.POST.get('quantity'))
    basket = request.session.get('basket', {})

    if request.method == "POST":

        quantity = int(request.POST['quantity'])
        if id in basket:
            basket[id] = int(basket[id]) + quantity
        else:
            basket[id] = basket.get(id, quantity)

    request.session['basket'] = basket
    return render(request, 'basket/basket.html')


def amend_basket(request, id):
    """
    A view that amends the quantity of a product in the basket
    """
    basket = request.session.get('basket', {})

    if request.method == "POST":
        quantity = int(request.POST['quantity'])
        basket = request.session.get('basket', {})
        if quantity > 0:
            basket[id] = quantity
        else:
            basket.pop[id]
        request.session.modified = True

    return render(request, 'basket/basket.html')


def delete_from_basket(request, id):
    """
    A view that deletes the specified item from the basket
    """
    basket = request.session.get('basket', {})
    del basket[id]
    if not basket.items():
        request.session['product_count'] = 0
    request.session.modified = True
    return render(request, 'basket/basket.html')

basket/templates/basket/basket.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title%}Tartan Thom - Bag{% endblock %} 
{% block content %}

<div class="container tartan-thom-container p-3 my-5">
    <div class="row justify-content-center m-2 p-3">
        <div class="col-md-12 col-lg-8">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <h1>My Bag</h1>
                </div>
            </div>
        </div>
    </div>

    {% if basket_items %}
    <div class="row justify-content-center m-1 p-3">
        <div class="col-md-12 col-lg-8">
            <a href="{% url 'products:view_products' %}" class="btn checkout-btn btn-md">
                <span>
                    <i class="fas fa-shopping-bag"></i>
                </span>
                <span>Continue shopping</span>
            </a>
        </div>
    </div>
    {% for item in basket_items %}
    <div class="row justify-content-center m-2 p-3">
        <div class="col-md-12 col-lg-8">
            <div class="row">
                <div class="col-md-4 my-1">
                    <img src="{{ item.product.image.url }}" alt="product-image" class="products-image"/>
                    {% if item.product.label %}
                    <div class="product-label-left py-auto">
                        <span class="label">{{ item.product.label }}</span>
                    </div>
                    {% endif %}
                </div>

                <div class="col-md-6 my-1">
                    <h2>{{ item.product.name }}</h2>
                    {% if item.product.sale_price %}
                    <p>
                        <span>{{ item.quantity }}</span> x <span>£{{ item.product.sale_price}}</span>
                    </p>
                    {% else %}
                    <p>
                        <span>{{ item.quantity }}</span> x <span>£{{ item.product.price}}</span>
                    </p>
                    {% endif %}
                    <form method="POST" action="{% url 'basket:amend_basket' item.product.id %}">         
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Quantity</label>
                            <input type="number" name="quantity" min="1" max="50">
                        </div>
                        <div class="form-row my-1">
                            <div class="col-md-3 col-xs-6 my-1">
                                <button class="add-to-basket btn btn-md" type="submit">Update</button>
                            </div>
                        </div>
                    </form>

                    <form method="POST" action="{% url 'basket:delete_from_basket' item.product.id %}">
                        {% csrf_token %}
                        <button type="submit" class="delete-from-basket btn float-left"><i class="far fa-trash-alt"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <hr>
    {% endfor %}
    <div class="row justify-content-center m-2 p-3">
        <div class="col-md-12 col-lg-8">
            {% if product_count == 1%}
                <h3>There is {{ product_count }} item in your bag</h3>
            {% else %}
                <h3>There are {{ product_count }} items in your bag</h3>
            {% endif %}
            <p>Items: £{{ order_total }}</p>
            <p>Delivery: £{{ delivery_total }}</p>
            <p>Total: £{{ grand_total }}</p>
        </div>
        <div class="col-md-12 col-lg-8 my-3">
            <a href="{% url 'checkout:checkout' %}" class="btn checkout-btn btn-md">Proceed to Checkout</a>
        </div>
    </div>
    {% else %}
    <div class="row justify-content-center m-2 p-3">
        <div class="col-md-12 col-lg-8 my-3">
            <h3>Sorry, you don't have any items in your bag!</h3>
        </div>
        <div class="col-md-12 col-lg-8 my-3">
            <p>
                <a href="{% url 'products:view_products' %}" class="btn checkout-btn btn-md">
                    <span>
                        <i class="fas fa-shopping-bag"></i>
                    </span>
                    <span>Continue shopping</span>
                </a>
            </p>
        </div>
    </div>
    {% endif %} 

</div>

{% endblock %}