about/urls.py
from django.urls import path
from about.views import about, about_design, about_philosophy

app_name = 'about'
urlpatterns = [
    path('', about, name='about'),
    path('design/', about_design, name='about_design'),
    path('philosophy/', about_philosophy, name='about_philosophy'),
]

basket/urls.py
from django.urls import path
from .views import view_basket, add_to_basket, amend_basket, delete_from_basket


app_name = 'basket'
urlpatterns = [
    path('', view_basket, name='view_basket'),
    path('add/<id>/', add_to_basket, name='add_to_basket'),
    path('amend/<id>/', amend_basket, name='amend_basket'),
    path('delete/<id>/', delete_from_basket, name='delete_from_basket'),
]

contact/urls.py
from django.urls import path
from contact.views import contact, faq

app_name = 'contact'
urlpatterns = [
    path('', contact, name='contact'),
    path('faq/', faq, name='faq'),
]

home/urls.py
from django.urls import path
from profiles.views import testimonial

app_name = 'home'
urlpatterns = [
    path('testimonial/', testimonial, name='testimonial'),
]

products/urls.py
from django.urls import path
from products.views import view_products, view_products_by_type, view_product, review_product


app_name = 'products'
urlpatterns = [
    path('', view_products, name='view_products'),
    path('products_by_type/<product_type>/', view_products_by_type,
         name='view_products_by_type'),
    path('view-product/<id>/', view_product, name='view_product'),
    path('review-product/<id>/', review_product, name='review_product'),
]

tartanthom/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls', namespace=None)),
    path('about/', include('about.urls', namespace=None)),
    path('contact/', include('contact.urls', namespace=None)),
    path('products/', include('products.urls', namespace=None)),
    path('basket/', include('basket.urls', namespace=None)),
    path('checkout/', include('checkout.urls', namespace=None)),
    path('profiles/', include('profiles.urls', namespace=None)),
    path('home/', include('home.urls', namespace=None)),
    path('', index, name='index'),
]

templates/base.html
{% load static %}
{% load bootstrap_tags %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}{% endblock %}</title>
    {% block main_css %}
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Open+Sans&family=Parisienne&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/font-awesome/css/all.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% endblock %}
    
    {% block extra_css %}
    {% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light nav-brand">
      <a class="navbar-brand" href="{% url 'index' %}"
        ><img
          class="brand"
          src="{% static 'img/brand.png' %}"
          alt="Tartan Thom Logo"
      /></a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:view_products' %}"><i class="fas fa-tags"></i>Shop</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            ><i class="fas fa-user"></i>
              Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'profiles:my_profile' %}">My Account</a>
                <a class="dropdown-item" href="{% url 'account_logout' %}">Log Out</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basket:view_basket' %}"><i class="fas fa-shopping-bag"></i>Bag
                {% if request.session.product_count %}
                <span class="bag-quantity">
                    {{ request.session.product_count }}
                </span>
                {% endif %}
            </a>
          </li>
        </ul>
      </div>
    </nav>

    {% block extra_nav %}
    {% endblock %}
    
    {% if messages %} 
        {% for message in messages %}
            <div id="django-alert" class="alert alert-{{message.tags}}">{{ message }}</div>
        {% endfor %}    
    {% endif %} 

    <div class="content">
    {% block content %} 
    {% endblock %}
    </div>

    <footer>
      <div class="container footer-container">
        <div class="row footer-row">
          <div class="footer-col footer-about col-md-4">
            <h3>About</h3>
            <p>
              <a class="footer-link" href="{% url 'about:about' %}">About Us</a>
            </p>
            <p>
              <a class="footer-link" href="{% url 'about:about_design' %}"
                >Design & Craft</a
              >
            </p>
            <p>
              <a class="footer-link" href="{% url 'about:about_philosophy' %}"
                >Philosophy</a
              >
            </p>
          </div>
          <div class="footer-col footer-contact col-md-4">
            <h3>Contact</h3>
            <p>
              <a class="footer-link" href="{% url 'contact:contact' %}"
                >Contact Us</a
              >
            </p>
            <p>
              <a class="footer-link" href="{% url 'contact:faq' %}">FAQs</a>
            </p>
          </div>
          <div class="footer-col footer-social col-md-4">
            <h3>Social</h3>
            <a href="https://twitter.com/TartanThom" target="_blank"
              ><i class="social fab fa-twitter-square footer-link"></i
            ></a>
            <a href="https://www.facebook.com/tartanthom/" target="_blank"
              ><i class="social fab fa-facebook-square footer-link"></i
            ></a>
            <a href="https://www.instagram.com/tartanthom/" target="_blank"
              ><i class="social fab fa-instagram-square footer-link"></i
            ></a>
          </div>
        </div>
        <div class="row footer-row">
          <div class="col-md-12 d-flex justify-content-center">
            <div class="copyright">
              <i class="fas fa-copyright"></i>Designed and built by Joojoobee
              2020
            </div>
          </div>
        </div>
      </div>
    </footer>

    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- Stripe -->
    <script src="https://js.stripe.com/v3/"></script>

    {% block postloadjs %}
    {% endblock %}
  </body>
</html>