basket/urls.py
from django.urls import path
from .views import view_basket, add_to_basket, amend_basket, delete_from_basket


app_name = 'basket'
urlpatterns = [
    path('', view_basket, name='view_basket'),
    path('add/<id>/', add_to_basket, name='add_to_basket'),
    path('amend/<id>/', amend_basket, name='amend_basket'),
    path('delete/<id>/', delete_from_basket, name='delete_from_basket'),
]

home/urls.py
from django.urls import path
from profiles.views import testimonial

app_name = 'home'
urlpatterns = [
    path('testimonial/', testimonial, name='testimonial'),
]

products/urls.py
from django.urls import path
from products.views import view_products, view_products_by_type, view_product, review_product


app_name = 'products'
urlpatterns = [
    path('', view_products, name='view_products'),
    path('products_by_type/<product_type>/', view_products_by_type,
         name='view_products_by_type'),
    path('view-product/<id>/', view_product, name='view_product'),
    path('review-product/<id>/', review_product, name='review_product'),
]

tartanthom/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls', namespace=None)),
    path('about/', include('about.urls', namespace=None)),
    path('contact/', include('contact.urls', namespace=None)),
    path('products/', include('products.urls', namespace=None)),
    path('basket/', include('basket.urls', namespace=None)),
    path('checkout/', include('checkout.urls', namespace=None)),
    path('profiles/', include('profiles.urls', namespace=None)),
    path('home/', include('home.urls', namespace=None)),
    path('', index, name='index'),
]

products/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User

# Create your models here.


class Products(models.Model):

    class Meta:

        verbose_name_plural = 'Products'

    PRODUCT_TYPE = [
        ('cards', 'Cards'),
        ('cake-toppers', 'Cake-Toppers'),
        ('gifts', 'Gifts')
    ]
    category = [
        ('Birthday', 'Birthday'),
        ('Wedding', 'Wedding'),
        ('Anniversary', 'Anniversary'),
        ('New Home', 'New Home'),
        ('Baby', 'Baby'),
        ('Leaving', 'Leaving'),
    ]
    labels = [
        ('New', 'New'),
        ('Sale', 'Sale')
    ]
    sizes = [
        ('A4', 'A4'),
        ('A5', 'A5'),
        ('200mm x 200mm', '200mm x 200mm'),
        ('122mm x 172mm', '122mm x 172mm'),
        ('172mm x 122mm', '172mm x 122mm'),
        ('250mm x 250mm', '250mm x 250mm'),
        ('210mm x 297mm', '210mm x 297mm'),
        ('152mm x variable', '152mm x variable'),
    ]
    name = models.CharField(max_length=100)
    product_type = models.CharField(max_length=100, choices=PRODUCT_TYPE)
    image = models.ImageField(upload_to='img',
                              default='static/img/TartanThomDefault.jpg')
    description = models.TextField()
    category = models.CharField(max_length=100, choices=category)
    price = models.DecimalField(decimal_places=2, max_digits=5)
    sale_price = models.DecimalField(null=True, decimal_places=2, max_digits=5)
    size = models.CharField(max_length=100, choices=sizes)
    label = models.CharField(blank=True, max_length=100, choices=labels)
    tags = models.CharField(blank=True, max_length=100)
    is_bespoke = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class ProductReviews(models.Model):

    class Meta:

        verbose_name_plural = 'Product Reviews'

    user = models.ForeignKey(
        User,
        models.SET_NULL,
        blank=True,
        null=True,
    )
    user_anonymous = models.BooleanField(default=False)
    product = models.ForeignKey(Products, null=False, on_delete=models.CASCADE)
    review_text = models.TextField(null=False, max_length=300)
    review_rating = models.IntegerField(null=False, default=5,
                                        validators=[MinValueValidator(1), MaxValueValidator(5)])
    review_date = models.DateField(auto_now_add=True)
    review_active = models.BooleanField(default=True)

    def __str__(self):

        return self.user.username

    def review_percentage(self):
        return int((self.review_rating / 5) * 100)

products/forms.py
from django import forms
from products.models import ProductReviews


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReviews

        fields = ('review_rating', 'review_text', 'user_anonymous')

        widgets = {
            'review_rating': forms.NumberInput(
                attrs={'localize': False, 'required': True}),
            'review_text': forms.Textarea(
                attrs={'required': True, 'rows': 5, 'cols': 20}),
            'user_anonymous': forms.CheckboxInput(
                attrs={'required': False, 'null': False}),
        }

        labels = {
            'review_rating': 'Rating',
            'review_text': 'Product Review',
            'user_anonymous': 'Prefer to remain anonymous?',
        }

        help_texts = {
            'review_rating': 'Enter a rating from 1-5 (1=Poor, 5=Excellent)',
            'review_text': 'Tell us a bit about why you love this product',
            'user_anonymous': 'Would you prefer your review to be anonymous to other customers?',
        }

        error_messages = {
            'review_text': {
                'max_length': "Try keep it short and sweet, maximum 500 characters",
                'required': "This field is required",
            },
            'review_rating': {
                'required': "This field is required",
                'min_value': "The minimum value is 1",
                'max_value': "The maximum value is 5",
            }
        }

products/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib import messages
from products.models import Products, ProductReviews
from products.forms import ReviewForm
import datetime

# Create your views here.


def view_products(request):
    """
    View all products in the collection
    """
    products = Products.objects.all()
    product_type = "All Products"
    results_count = products.count()
    context = {
        'products': products,
        'product_type': product_type,
        'results_count': results_count,
    }
    return render(request, "products/products.html", context)


def view_products_by_type(request, product_type):
    """
    View all products with the product type 'Cards'
    """
    if request.method == 'GET':
        products = Products.objects.filter(product_type=product_type)
        results_count = products.count()
        context = {
            'products': products,
            'product_type': product_type,
            'results_count': results_count,
        }
    else:
        messages.error(request, "Sorry, there are no products of this type")
        return redirect(reverse('view_products'))
    return render(request, "products/products.html", context)


def view_product(request, id):
    """
    View selected product in the collection
    """
    product = get_object_or_404(Products, pk=id)
    reviews = ProductReviews.objects.filter(product=id)
    context = {
        'product': product,
        'reviews': reviews,
    }
    return render(request, "products/product.html", context)


def review_product(request, id):
    """
    Review form for user to submit for a specific product
    """
    form = ReviewForm()
    product = get_object_or_404(Products, pk=id)
    context = {
            'form': form,
            'product': product,
    }

    if request.method == 'POST':
        form_data = {
            'review_rating': request.POST['review_rating'],
            'review_text': request.POST['review_text'],
            'user_anonymous': request.POST.get('user_anonymous', False)
        }
        form = ReviewForm(form_data)
        if form.is_valid():
            review = form.save(commit=False)
            review.review_date = datetime.datetime.now()
            review.user = request.user
            review.product = product
            review.save()
            messages.success(request, 'Thanks for submitting your review!')
            return redirect(reverse('profiles:my_profile'))
        else:
            messages.error(request, 'Please check the information in the form')

    return render(request, 'products/review_product.html', context)

products/templates/products/product.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title%}Tartan Thom Shop - {{ product.name }}{% endblock %} 
{% block content %}

<div class="container p-3 my-5">
    <div class="row justify-content-center my-1">
        <div class="col-md-4 m-2 p-0">
            <img src="{{ product.image.url }}" alt="product-image" class="products-image"/>
            {% if product.label %}
            <div class="product-label py-auto">
                <span class="label">{{ product.label }}</span>
            </div>
            {% endif %}
        </div>
        <div class="col-md-6 product-details m-2">
            <h2>{{ product.name }}</h2>
            <p>Category: {{ product.category }}</p>
            {% if product.sale_price %}
                <p><span class="strike">£{{ product.price }}</span>   £{{ product.sale_price }}</p>
            {% else %}
                <p>£{{ product.price }}</p>
            {% endif %}
            <form method="POST" action="{% url 'basket:add_to_basket' product.id %}">
                {% csrf_token %}
                <div class="form-group">
                    <label>Quantity</label>
                    <input type="number" name="quantity" min="1" max="50">
                </div>
                <div class="form-row my-2">
                    <div class="col-md-12">
                        <button class="add-to-basket btn" type="submit">Add to bag</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row justify-content-center my-1">
        <div class="col-md-10 my-1">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="description-tab" data-toggle="tab" href="#description"
                    role="tab" aria-controls="description" aria-selected="true">Description</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="reviews-tab" data-toggle="tab" href="#reviews" role="tab"
                    aria-controls="reviews" aria-selected="false">Reviews</a>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
                <p class="py-1">{{ product.description }}</p>
                <p class="py-1">Size: {{ product.size }}</p>
                {% if product.is_bespoke %}
                <p class="py-1">This is a bespoke product so we'll collect further details once you've completed your order. Bespoke forms can be found via Account - Order History - Order Detail</p>
                {% endif %}
            </div>
            <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
            {% if reviews %}
                {% for review in reviews %}
                    {% if review.user_anonymous %}
                        <div>Customer: Anonymous</div>
                    {% else %}
                        <div>Customer: {{ review.user.username }}</div>
                    {% endif %}
                    <div>Date: {{ review.review_date }}</div>
                    <div class="stars">
                        <div class="stars-filling" style="width: {{review.review_percentage}}%;"></div>
                    </div>
                    <div class="review-text">{{ review.review_text }}</div>
                    <hr>
            {% endfor %}
        {% else %}
            <div>There are no reviews for this product yet!</div>
        {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

products/templates/products/products.html
{% extends 'base.html' %} 
{% load static %} 
{% block title%}Tartan Thom - Shop{% endblock %} 

{% block extra_nav %}

<nav id="nav-shop" class="navbar navbar-expand-lg nav-shop">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:view_products' %}">All Products</a>
                    </li>                    
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:view_products_by_type' 'cards' %}">Cards</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:view_products_by_type' 'cake-toppers' %}">Cake Toppers</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:view_products_by_type' 'gifts' %}">Gifts</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

{% endblock %}

{% block content %}

<div class="container tartan-thom-container p-3 my-5">
    <div class="row justify-content-center m-1 p-3">
        <div class="col">
            <h1>Products</h1>
        </div>
    </div>
    <div class="row justify-content-center mx-3 p-3">
        <div class="col-md-6 my-1">
            <h3>{{ product_type|title }}:</h3>
        </div>
        <div class="col-md-6 my-1">
        {% if products %}
            <h3>Found {{ results_count }} results to match your search</h3>
        {% else %}
            <h3>Sorry, we didn't find any products of this type</h3>
        {% endif %}
        </div>
    </div>
    <div class="row justify-content-center m-2 p-3">
        {% if products %}
            {% for product in products %}
            <div class="product-panel col-md-3 col-sm-5 m-3">
                <div class="row justify-content-center">
                    <div class="product-panel">
                        <div class="product-panel-image">
                            <a href="{% url 'products:view_product' product.id %}">
                                {% if product.image.url %}
                                <img class="products-image" src="{{ product.image.url }}" alt="product-image"/>
                                {% else %}
                                <img class="products-image" src="{% static 'img/TartanThomDefault.jpg' %}" alt="product-image"/>
                                {% endif %}
                                {% if product.label %}
                                <div class="product-label py-auto">
                                    <span class="label">{{ product.label }}</span>
                                </div>
                                {% endif %}
                            </a>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-12 product-panel-details">
                        <h2>{{ product.name }}</h2>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-12 product-panel-details">
                        {% if product.sale_price %}
                        <p><span class="strike">£{{ product.price }}</span>   £{{ product.sale_price }}</p>
                        {% else %}
                        <p>£{{ product.price }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %} 
        {% endif %}
    </div>
</div>

{% endblock %}

products/templates/products/review_product.html
{% extends 'base.html' %} 
{% load static %} 
{% load crispy_forms_tags %}
{% block title%}Tartan Thom - Review Product{% endblock %} 

{% block content %}

<div class="container tartan-thom-container p-3 my-5">
    <div class="row justify-content-center m-2 p-3">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-8 px-3 mx-auto">
                    <h1>Product Reviews</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 px-3 mx-auto">
                    <form action="{% url 'products:review_product' product.id %}" method="POST">
                    {% csrf_token %}
                        <!-------------Customer Details----------->
                        <div class="col-md-12 px-3 mx-auto">
                            <fieldset class="mb-5">
                                <div>
                                    {{ form|crispy }}
                                </div>
                            </fieldset>
                            <fieldset class="mb-5">
                                <button type="submit" class="btn tartan-thom-btn">Submit</button>
                            </fieldset>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}